### PR TITLE
Read DOM feature

### PR DESCRIPTION
**Pull request by sinster2003**
Description of Code

1.  The readContent function returns an object containing the read function. The user can access it by calling that method.
2.  The read function does few things:

-  Returns attributes value if present in the html element
-  **Extra feature**: Also returns DOM element property like innerHTML, innerText, textContent reading the html elements but properties which return objects like style, dataset is considered invalid and  they are handled in attributes section if and only if they are added to html elements.
- all is true, returns an array of html elements if attributes not specified ,if a valid attribute is specified returns the array of value of those attributes            
- The read function can take two parameters like read(selector,all) or three parameters read(selector,attribute,all)
- Extra functions are written to validate attributes and properties
- The thought process is all that ---> property is valid if it returns a string, if returns an object it is invalid
- and all attributes are valid if there exists one and they are added to html elements.

Any feedbacks or suggestions are gladly accepted and do ask the working of code if there are any clarifications

### CODE REVIEW

**Comment by lindelwa122** [comment]
Hey, @sinster2003, thanks for your efforts on this feature. I appreciate your approach, but there are a few aspects that could use improvement.

The wording might have been a bit misleading in my initial instructions. The goal is not only to retrieve a specific attribute of an element but to access all of its properties. For instance, you used `getAttribute()` to obtain a property or attribute of an element. While `getAttribute('class')` will return the class names of an element, `getAttribute('className')` will return `null`. Similarly, `getAttribute()` returns `null` for other values like `style`, `innerHTML`, etc. Instead of using `getAttribute()`, you should use this syntax: `element[propertyName]`. To maintain clarity, we can rename the parameter from `attributeName` to `propertyName`.

Regarding the `attributeValidation` function, we don't need it to be overly complex. The key point is to throw an error if `element[propertyName]` is undefined.

Additionally, it's a convention to prefix all private methods and variables with an underscore. Please remember to document your method in the DOCS file. Thank you!

**Comment by sinster2003** [comment]
@lindelwa122 ya I got your point will improve on these aspects

**Comment by sinster2003** [comment]
As an update, @lindelwa122 worked on the improvements, removed all the complexities of the code and property syntax is used... working on the documentation will edit the pull request soon.

**Comment by sinster2003** [comment]
@lindelwa122 got some branch conflicts will resolve soon for a PR

**Pull request closed without merging**
